version: "3.9"

services:
  app:
    build: ./backend
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html  
    depends_on:
      - db
      
  frontend:
    build: ./frontend
    container_name: react_app
    restart: unless-stopped
    volumes:
     - ./frontend:/app
    ports:
      - "3000:3000"
  db:
    image: postgres:15
    container_name: notes_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password 
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
      - ./frontend:/var/www/html/frontend
    ports:
      - "80:80"
    depends_on:
      - app
      - frontend


